### ISSUE TITLE
TRRT error converter does no conversion (but it does execute on an error)

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#43]
I have specified the following TRRT configuration: 

``` yaml
## Term Reference Resolution Tool
trrt:
  interpreter: default 
  converter: html-hovertext-link
  converter[error]: "{{showtext}}{{log 'TRRT error converter:' err.dir '/' err.file '@' err.line ':' err.pos '[' ref.showtext ']' level='warn'}}"
```

I would expect that this configuration would have the following effect for any TermRef for which it could not find a corresponding MRG-entry:

- [x] it would write a log-text, stating the directory/file + line:pos + the showtext of the TermRef (which it does)
- [x] it would replace the Termref with its showtext (which it doesn't). Instead, it leaves the TermRef intact.

The idea of the `converter[error]` is that the TermRef will actually be replaced by what it says.
